//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointment_ManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentRecommendation
    {
        public int AppointmentRecommendationsId { get; set; }
        public string Recommendation { get; set; }
        public Nullable<int> AppointmentId { get; set; }
    
        public virtual appointment appointment { get; set; }
    }
}
